baseURL = "https://tutor01.onrender.com/"
languageCode = "ru-ru"
title = "Tutorial"
theme = "minos2"
paginate = 10

[params]
	smartToc = true
	oPostNavigation = true
	customCss = ["css/foo.css"]
[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = -110
